// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  apiKey: "AIzaSyD0wsmwziRfkE_PQLdx3s0oYMj2a9Ru8cY",
  authDomain: "optifitaicopy-87674237-d47c0.firebaseapp.com",
  projectId: "optifitaicopy-87674237-d47c0",
  storageBucket: "optifitaicopy-87674237-d47c0.appspot.com",
  messagingSenderId: "620460614828",
  appId: "1:620460614828:web:5adecf67678f4467e7eb09",
  measurementId: "G-MEASUREMENT_ID"
};
